"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

# Next.js on-demand revalidation
NEXTJS_URL = os.getenv('NEXTJS_URL', 'http://localhost:3000')
REVALIDATION_SECRET = os.getenv('REVALIDATION_SECRET', '')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'django_ckeditor_5',
    'customers',
    'products',
    'services',
    'auth_app',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

AUTH_USER_MODEL = 'customers.Customer'

# --- DRF & CORS SETTINGS ---

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Разрешаем запросы с хостов, указанных в ALLOWED_HOSTS + стандартные порты Next.js
# Это делает настройку гибкой: поменял домен в .env — поменялся и тут.
def _build_origins() -> list[str]:
    origins = []
    for host in ALLOWED_HOSTS:
        if host in ('*', ''):
            continue
        origins.append(f"http://{host}")
        # Для доменных имён (не IP, не localhost) добавляем HTTPS
        if not host[0].isdigit() and host not in ('localhost',):
            origins.append(f"https://{host}")
    origins += [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    return origins

CORS_ALLOWED_ORIGINS = _build_origins()

# Для Next.js важно доверять этим источникам при передаче cookies (CSRF)
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

CORS_ALLOW_CREDENTIALS = True # Разрешаем куки (важно для авторизации)

# Настройки сессий (как у тебя было, но чуть чище)
SESSION_COOKIE_AGE = 86400
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'

# Статика и Медиа
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/imperia/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/imperia/media'

# CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', 'strikethrough',
            '|', 'bulletedList', 'numberedList', 'blockQuote',
            '|', 'link', 'imageUpload', '|', 'undo', 'redo',
        ],
        'language': 'ru',
    },
}
CKEDITOR_UPLOAD_PATH = 'blog_content/'

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

# --- Jazzmin Admin Rebranding ---
STATICFILES_DIRS = [BASE_DIR / 'static']

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

JAZZMIN_SETTINGS = {
    # branding
    'site_header': 'Империя Электроники',
    'site_brand': '',
    'site_logo': 'logo.png',
    'site_logo_classes': 'elevation-3',
    'welcome_sign': 'Добро пожаловать в админ-панель',
    'copyright': 'Империя Электроники © 2026',

    # colors (DESIGN.md)
    'site_title': 'Админка | Империя',
    'site_logo_color': '#1061cd',
    'login_logo': 'logo.png',
    'login_logo_dark': 'logo.png',

    # theme
    'theme': 'flatly',
    'dark_mode_theme': None,

    # UI toggles
    'show_sidebar': True,
    'navigation_expanded': True,
    'show_ui_builder': False,
    'related_modal_active': True,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'products.product': 'horizontal_tabs',
        'products.category': 'horizontal_tabs',
    },

    # custom CSS
    'custom_css': 'admin/css/imperia.css',
    'custom_js': None,

    # icons per model
    'icons': {
        'customers.customer': 'fas fa-users',
        'products.product': 'fas fa-box',
        'products.category': 'fas fa-folder-tree',
        'products.brand': 'fas fa-tag',
        'products.attribute': 'fas fa-list-ul',
        'products.tag': 'fas fa-hashtag',
        'services.serviceitem': 'fas fa-tools',
        'notifications.notification': 'fas fa-bell',
    },

    # top menu links
    'topmenu_links': [
        {'name': 'Главная', 'url': '/', 'new_tab': True},
        {'name': 'Сайт', 'url': 'http://localhost:3000', 'new_tab': True},
    ],

    # user menu
    'usermenu_links': [
        {'name': 'Сайт', 'url': 'http://localhost:3000', 'new_tab': True},
    ],
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-white',
    'accent': 'accent-primary',
    'navbar': 'navbar-white navbar-light',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'flatly',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
