# Generated by Django 6.0.4 on 2026-07-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_coupon_loyaltyprogram_couponusage_customerloyalty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Основные уведомления'", max_length=100, unique=True, verbose_name='Название настройки')),
                ('telegram_enabled', models.BooleanField(default=True, verbose_name='Включить Telegram уведомления')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата для отправки уведомлений', max_length=100, verbose_name='Telegram Chat ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Включить Email уведомления')),
                ('email_address', models.EmailField(blank=True, help_text='Адрес для отправки уведомлений', max_length=254, verbose_name='Email адрес')),
                ('notify_new_orders', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('notify_status_changes', models.BooleanField(default=False, verbose_name='Уведомлять об изменении статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], max_length=20, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка'), ('pending', 'Ожидание')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('recipient', models.CharField(help_text='Chat ID для Telegram или email адрес', max_length=255, verbose_name='Получатель')),
                ('error_message', models.TextField(blank=True, help_text='Описание ошибки, если отправка не удалась', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='customers.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
