# Generated by Django 6.0.4 on 2026-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, to='products.brand', verbose_name='Бренды категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, to='products.brand', verbose_name='Бренды'),
        ),
    ]
