# Generated by Django 6.0.4 on 2026-07-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_product_feature_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('name', models.CharField(help_text='Например: «16 ГБ / 512 ГБ SSD, Чёрный»', max_length=255, verbose_name='Название варианта')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указана, используется цена товара.', max_digits=10, null=True, verbose_name='Цена варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'ordering': ['sort_order', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(default='default', help_text="Идентификатор склада (например, 'msk', 'spb').", max_length=100, verbose_name='Склад')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attribute',
            name='enum_options',
            field=models.JSONField(blank=True, help_text='Список допустимых значений для типа \'enum\', например: ["Красный", "Синий", "Чёрный"]', null=True, verbose_name='Варианты перечисления'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('str', 'Строка'), ('int', 'Целое число'), ('bool', 'Булево (Да/Нет)'), ('enum', 'Перечисление')], default='str', help_text='Определяет, как хранится и фильтруется значение атрибута.', max_length=10, verbose_name='Тип значения'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True, verbose_name='Булево значение'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_enum',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение перечисления'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='Числовое значение'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_str',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Строковое значение'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'Основное фото'), ('gallery', 'Галерея'), ('360', 'Панорама 360°'), ('video_poster', 'Постер видео')], default='gallery', max_length=20, verbose_name='Тип изображения'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(default=False, help_text='Отзыв от клиента, который действительно купил этот товар.', verbose_name='Подтверждённая покупка'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['type', 'slug'], name='products_at_type_f4fcf3_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Вариант'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'attribute'], name='products_pr_product_94a04a_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['variant', 'attribute'], name='products_pr_variant_989f38_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['attribute', 'value_int'], name='products_pr_attribu_87c5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['attribute', 'value_enum'], name='products_pr_attribu_4705f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('product', 'attribute'), name='unique_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='unique_variant_attribute'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='products.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='products_st_product_282fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['variant', 'warehouse'], name='products_st_variant_10937e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('product', 'warehouse'), name='unique_product_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_variant_warehouse'),
        ),
    ]
