# Generated by Django 6.0.4 on 2026-07-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_stock_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promo_banners/', verbose_name='Баннер')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем приоритетнее акция при наложении.', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, help_text='Если не указан, используется название категории.', max_length=255, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если не указан, используется название категории.', max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='h1',
            field=models.CharField(blank=True, help_text='Если не указан, используется название товара.', max_length=255, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если не указан, используется название товара.', max_length=255, verbose_name='Meta Title'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='Изображение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Фото отзыва',
                'verbose_name_plural': 'Фото отзывов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('reason', models.CharField(blank=True, help_text='Например: «Акция», «Изменение курса», «Обновление прайса поставщика».', max_length=255, verbose_name='Причина изменения')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['product', '-changed_at'], name='products_pr_product_f0e7be_idx'), models.Index(fields=['variant', '-changed_at'], name='products_pr_variant_9e2fe6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'Фиксированная сумма'), ('percent', 'Процент'), ('new_price', 'Фиксированная цена')], max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Для fixed — сумма в валюте, для percent — процент (0–100), для new_price — новая цена.', max_digits=10, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Скидка применяется при покупке от указанного количества.', verbose_name='Минимальное количество')),
                ('category', models.ForeignKey(blank=True, help_text='Скидка применяется ко всем товарам в категории.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.productvariant', verbose_name='Вариант')),
                ('promo_campaign', models.ForeignKey(blank=True, help_text='Оставьте пустым, если скидка не привязана к акции.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.promocampaign', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_di_product_33ad43_idx'), models.Index(fields=['variant', 'is_active'], name='products_di_variant_7129c4_idx'), models.Index(fields=['category', 'is_active'], name='products_di_categor_a1a6ee_idx')],
            },
        ),
    ]
