# Generated by Django 6.0.4 on 2026-07-07 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_country_brand_description_brand_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='Мобильное изображение')),
                ('link', models.URLField(blank=True, help_text='Куда ведёт баннер при клике.', verbose_name='Ссылка')),
                ('placement', models.CharField(choices=[('home_top', 'Главная — верх'), ('home_middle', 'Главная — середина'), ('category_top', 'Категория — верх'), ('sidebar', 'Боковая панель')], default='home_top', max_length=20, verbose_name='Размещение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, help_text='Для баннеров категорий.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['placement', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «Сертификат Ростест», «Инструкция по эксплуатации».', max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='PDF-файл')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Сертификат / документ',
                'verbose_name_plural': 'Сертификаты / документы',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Категории в блоке')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Товары в блоке')),
            ],
            options={
                'verbose_name': 'Промо-блок',
                'verbose_name_plural': 'Промо-блоки',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «Гарантия производителя», «Расширенная гарантия».', max_length=255, verbose_name='Название')),
                ('duration_value', models.PositiveIntegerField(default=12, verbose_name='Срок')),
                ('duration_unit', models.CharField(choices=[('days', 'Дней'), ('months', 'Месяцев'), ('years', 'Лет')], default='months', max_length=10, verbose_name='Единица срока')),
                ('description', models.TextField(blank=True, verbose_name='Условия гарантии')),
                ('document', models.FileField(blank=True, null=True, upload_to='warranty_docs/', verbose_name='PDF-документ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('excerpt', models.TextField(blank=True, help_text='Отображается в списке статей.', verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Связанные товары')),
                ('tags', models.ManyToManyField(blank=True, to='products.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='products_bl_status_aab172_idx')],
            },
        ),
    ]
