# Generated by Django 6.0.4 on 2026-07-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_supplier_banner_certificate_promotionblock_warranty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден на главной')),
                ('is_visible_by_default', models.BooleanField(default=False, verbose_name='Виден обычным админам')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел админки',
                'verbose_name_plural': 'Видимость разделов админки',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат / документ', 'verbose_name_plural': 'Сертификаты / документы'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'Гарантия', 'verbose_name_plural': 'Гарантии'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное количество'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='platform',
            field=models.CharField(blank=True, max_length=50, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
