# Generated by Django 6.0.4 on 2026-07-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_adminsection_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отключайте, чтобы скрыть бренд на сайте без удаления из БД.', verbose_name='Активен'),
        ),
    ]
