# Generated by Django 6.0.4 on 2026-07-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для карточки категории на странице каталога.', null=True, upload_to='category_images/', verbose_name='Изображение'),
        ),
    ]
