# Generated by Django 6.0.4 on 2026-07-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_provenance',
            field=models.CharField(blank=True, default='manual', help_text='Откуда взят логотип: manual, newegg_scrape, etc.', max_length=30, verbose_name='Источник логотипа'),
        ),
    ]
