# Generated by Django 6.0.4 on 2026-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand_logo_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='provenance',
            field=models.CharField(blank=True, default='web', help_text='Откуда получено изображение: web, newegg_scrape, manual, etc.', max_length=30, verbose_name='Источник изображения'),
        ),
    ]
