# Generated by Django 6.0.4 on 2026-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_productimage_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Если включено, статья не будет индексироваться поисковиками.', verbose_name='Запретить индексацию'),
        ),
        migrations.AddField(
            model_name='category',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Если включено, страница не будет индексироваться поисковиками.', verbose_name='Запретить индексацию'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_description',
            field=models.TextField(blank=True, help_text='Текстовый блок перед списком товаров. Поддерживает HTML.', verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Если включено, страница товара не будет индексироваться поисковиками.', verbose_name='Запретить индексацию'),
        ),
    ]
