# Generated by Django 6.0.4 on 2026-07-07 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cart_viewedproduct_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('discount_type', models.CharField(choices=[('fixed', 'Фиксированная сумма'), ('percent', 'Процент')], max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Сумма в валюте или процент (0–100).', max_digits=10, verbose_name='Значение')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — без ограничений.', verbose_name='Максимум использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Максимум на пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала действия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_orders', models.PositiveIntegerField(default=0, help_text='Количество заказов для достижения уровня.', verbose_name='Минимум заказов')),
                ('min_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма покупок')),
                ('discount_percent', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Персональная скидка (%)')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Приоритетная поддержка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок (от низшего к высшему)')),
            ],
            options={
                'verbose_name': 'Уровень лояльности',
                'verbose_name_plural': 'Уровни лояльности',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма скидки')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='customers.coupon', verbose_name='Купон')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Использование купона',
                'verbose_name_plural': 'Использования купонов',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Всего заказов')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего потрачено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.loyaltyprogram', verbose_name='Текущий уровень')),
            ],
            options={
                'verbose_name': 'Лояльность клиента',
                'verbose_name_plural': 'Лояльность клиентов',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Представление объекта')),
                ('changes', models.JSONField(default=dict, help_text='Словарь изменённых полей: {поле: {"old": ..., "new": ...}}.', verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменений',
                'verbose_name_plural': 'Логи изменений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='customers_c_model_n_b180dc_idx'), models.Index(fields=['-created_at'], name='customers_c_created_3f28da_idx')],
            },
        ),
    ]
